-- 1. Schema and types for both tables (answers most open questions at once)
SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM ANALYTICS_DEV_CONNOR.INFORMATION_SCHEMA.COLUMNS
WHERE (TABLE_SCHEMA, TABLE_NAME) IN (('SALES','SALES_MOVEMENT'), ('REPORTING','COMPETITOR_RAW'))
ORDER BY TABLE_NAME, ORDINAL_POSITION;

-- 2. Is SALES_MOVEMENT carrying cancellations?
SELECT COUNT(*) AS rows_all,
       COUNT_IF(PAX <= 0) AS rows_nonpositive_pax,
       COUNT_IF(GROSS_PRICE_USD <= 0) AS rows_nonpositive_price,
       MIN(PAX) AS min_pax, MAX(PAX) AS max_pax
FROM ANALYTICS_DEV_CONNOR.SALES.SALES_MOVEMENT
WHERE REGION_REPORT = 'USA' AND RELEVANT_DATE_LOCAL >= '2025-10-01';

-- 3. Per-person or per-booking? Look at the ratio across pax counts.
SELECT PAX, COUNT(*) AS n,
       ROUND(MEDIAN(GROSS_PRICE_USD)) AS med_gross,
       ROUND(MEDIAN(GROSS_PRICE_USD / NULLIF(PAX,0))) AS med_gross_per_pax,
       ROUND(MEDIAN(TOUR_NIGHTS)) AS med_nights
FROM ANALYTICS_DEV_CONNOR.SALES.SALES_MOVEMENT
WHERE REGION_REPORT = 'USA' AND RELEVANT_DATE_LOCAL >= '2025-10-01' AND PAX > 0
GROUP BY PAX ORDER BY PAX;

-- 4. The three scrape filters that can swing the index most
SELECT AIRFARE_LOCATION, ROOM_TYPE, SITE, COUNT(*) AS n,
       ROUND(MEDIAN(PRICE)) AS med_price, ROUND(MEDIAN(PRICE_PN)) AS med_price_pn
FROM ANALYTICS_DEV_CONNOR.REPORTING.COMPETITOR_RAW
WHERE CURRENCY = 'USD' AND SCRAPE_DATE >= '2025-10-01'
GROUP BY 1,2,3 ORDER BY n DESC LIMIT 50;

-- 5. Is COMPETITOR_RAW actually one row per tour/departure/scrape?
SELECT COUNT(*) AS rows_all,
       COUNT(DISTINCT SITE || TOUR_CODE || DEPARTURE_DATE || SCRAPE_DATE || ROOM_TYPE) AS rows_distinct
FROM ANALYTICS_DEV_CONNOR.REPORTING.COMPETITOR_RAW
WHERE CURRENCY = 'USD' AND SCRAPE_DATE >= '2025-10-01';

-- 6. Do PRICE_PN / PRICE_PD reconcile, and does PRICE = PRE_OFFER_PRICE - DISCOUNT_AMOUNT?
SELECT ROUND(MEDIAN(PRICE / NULLIF(TOUR_NIGHTS_NO_AIR,0)), 1) AS implied_pn,
       ROUND(MEDIAN(PRICE_PN), 1) AS stated_pn,
       ROUND(MEDIAN(PRE_OFFER_PRICE - DISCOUNT_AMOUNT - PRICE), 2) AS discount_reconciles_to_zero
FROM ANALYTICS_DEV_CONNOR.REPORTING.COMPETITOR_RAW
WHERE CURRENCY = 'USD' AND SCRAPE_DATE >= '2025-10-01';

-- 7. Which market column is the right filter?
SELECT REGION_REPORT, SELLING_REGION_NAME, AGENCY_COUNTRY, CURRENCY, COUNT(*) AS n
FROM ANALYTICS_DEV_CONNOR.SALES.SALES_MOVEMENT
WHERE RELEVANT_DATE_LOCAL >= '2025-10-01'
GROUP BY 1,2,3,4 ORDER BY n DESC LIMIT 30;
