SELECT BOOKING_ID, BOOKING_REFERENCE, NET_MOVEMENT_TYPE, STATUS_CODE,
       BOOKING_LINE_ITEM_TYPE, BOOKING_LINE_ITEM_STATUS_CODE,
       BOOKED_AT, ORIGINAL_BOOKINGDATE_LOCAL, FROM_DATE, BOOKING_TO_DEPARTURE_DAYS,
       PAX, BROCHURE_PRICE_CALCULATED, ORIGINAL_PRICE, GROSS_PRICE, GROSS_PRICE_USD,
       ASSUMED_DISCOUNT, PROMOTION_CODES, CX_REASON, IS_FTC, IS_BOOKING_QUOTE
FROM ANALYTICS_DEV_CONNOR.SALES.SALES_MOVEMENT
WHERE BOOKING_ID = (
    SELECT BOOKING_ID
    FROM ANALYTICS_DEV_CONNOR.SALES.SALES_MOVEMENT
    WHERE CX_REASON IS NOT NULL
    LIMIT 1
)
ORDER BY BOOKED_AT;

SELECT NET_MOVEMENT_TYPE, IS_FTC, IS_BOOKING_QUOTE,
       COUNT(*) AS n_rows, SUM(PAX) AS pax
FROM ANALYTICS_DEV_CONNOR.SALES.SALES_MOVEMENT
WHERE ORIGINAL_BOOKINGDATE_LOCAL >= '2025-09-01'
  AND UPPER(DIVISION_BRAND) = 'TOURING'
GROUP BY 1, 2, 3
ORDER BY n_rows DESC;

SELECT f.value::STRING AS promo_code,
       COUNT(DISTINCT s.BOOKING_ID)          AS n_bookings,
       MIN(s.ORIGINAL_BOOKINGDATE_LOCAL)::DATE AS first_used,
       MAX(s.ORIGINAL_BOOKINGDATE_LOCAL)::DATE AS last_used
FROM ANALYTICS_DEV_CONNOR.SALES.SALES_MOVEMENT s,
     LATERAL FLATTEN(input => s.PROMOTION_CODES) f
WHERE s.ORIGINAL_BOOKINGDATE_LOCAL BETWEEN '2025-10-01' AND '2025-12-31'
  AND UPPER(s.DIVISION_BRAND) = 'TOURING'
GROUP BY 1
ORDER BY n_bookings DESC
LIMIT 50;
